### PR TITLE
mobile/ Mobile branch is ready to merge into master branch.

### PR DESCRIPTION
**Pull request by sertayy**

### CODE REVIEW

**Review by yscaliskan — APPROVED** [review]
Feels good to see all our hard work of a semester :)

**Comment by kayacanv** [comment]
Thank you all, we added a lot to each other. You are one of the people I communicate with the most during this semester. 
Best Regards

**Review by kayacanv — APPROVED** [review]

**Review by emrehoser — APPROVED** [review]
Great team, great colleagues and great works. Thank you for all.

**Comment by sertayy** [comment]
It was a pleasure to work with you all. Good word as a team! Thanks :pray:

**Pull request merged**
