### PR TITLE
initial django project

### LINKED ISSUE #112: Back-End Project Initialization
- Learn Django in more depth.
- Initalize first back-end server repository.

Deadline:  08.11.2020 23:59

### LINKED ISSUE #114: Creating a MongoDB
we need to get a Mongo database.

### PR DESCRIPTION
**Pull request by yusufyuksel96**
Created first back-end repository and MongoDB for project initialization. Closes #112 and closes #114  .

### CODE REVIEW

**Review by thehalas — APPROVED** [review]
Perfect.

**Comment by volkanbulca** [comment]
Seems allright.

**Review by volkanbulca — APPROVED** [review]

**Comment by sarismet** [comment]
Perfect!!!.

**Review by sarismet — APPROVED** [review]
Well Done.

**Pull request merged**
