### PR TITLE
mobile- homepage for vendors

### PR DESCRIPTION
**Pull request by kayacanv**
Screen Shot 2021-01-25 at 23 27 04

### CODE REVIEW

**Review by emrehoser — APPROVED** [review]
Navigating a new activity after the vendor login is a good way to vendor-specific functionalities.

**Review by sertayy — CHANGES_REQUESTED** [review]
The info belowed add product section in the my account tab is the same as the info at help section. ("Frequently asked question". Could you change the add product info to a more related one like "Add your product to the platform"? Or you can simply delete it since "Add product" is clear enough for the user experience. Thanks.

Plus, you can use one of the images mentioned below instead of using :white_check_mark:. I think it would be more related to adding a product.
1. [Suggestion](https://www.flaticon.com/free-icon/add-to-cart_3759127?term=add%20product&page=1&position=4&page=1&position=4&related_id=3759127&origin=search)
2. [Suggestion](https://www.flaticon.com/free-icon/shopping-cart_2898094?term=add%20product&related_id=2898094)

**Comment by kayacanv** [comment]
I updated the icon and text bellow

**Comment by kayacanv** [comment]
I updated as you have requested

**Review by sertayy — APPROVED** [review]
Good work!

**Pull request merged**
