### PR TITLE
mobile/ Featured products are added to the home page.

### PR DESCRIPTION
**Pull request by sertayy**
Featured products: Recommended, trending, best sellers and trendings. I will design the pictures for each one them soon.

### CODE REVIEW

**Comment by sertayy** [comment]
Hi @kayacanv,

As we talked in the previous meeting I have changed the lateinit variables to "var" in the user class to distinguish the guest and verified user in the homepage. 

Here is the conflicts in the chatActivity.kt. I have already resolved it. Since you implemented this class I wanted to keep you updated. 

Ekran Resmi 2021-01-25 23 38 00

**Review by emrehoser — APPROVED** [review]
Recommendation methods and pages have good design and implementation.

**Review by yscaliskan — APPROVED** [review]
Your implementation looks really good! Only the word "spesific" in file and variable names might be refactored to "specific".

**Comment by sertayy** [comment]
> Your implementation looks really good! Only the word "spesific" in file and variable names might be refactored to "specific".

Good point @yscaliskan!. My bad, I need to study more on grammar 😞

**Pull request merged**
